version: "3.9"

services:
  go_db:
    container_name: go_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    environment:
      - DB_HOST=go_db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=postgres

volumes:
  pgdata: {}
